import { readdir } from "node:fs/promises";
import { digest } from "../packages/ontology/src/index";

const root = new URL("../", import.meta.url);
const names = [
  "package.json",
  "bun.lock",
  "tsconfig.json",
  "packages/agent/wrangler.jsonc",
];
async function collect(path: string) {
  for (const entry of await readdir(new URL(path, root), {
    withFileTypes: true,
  })) {
    const name = `${path}/${entry.name}`;
    if (entry.isDirectory()) await collect(name);
    else if (
      (name.endsWith(".ts") || name.endsWith(".sql")) &&
      !name.endsWith(".test.ts") &&
      !name.endsWith("/build-info.ts")
    )
      names.push(name);
  }
}
for (const path of [
  "packages/agent/src",
  "packages/pipeline/src",
  "packages/ontology/src",
  "packages/agent/migrations",
  "scripts",
])
  await collect(path);
const files: Record<string, string> = {};
for (const name of names.sort())
  files[name] = await Bun.file(new URL(name, root)).text();
const revision = await digest(files);
const target = new URL("packages/agent/src/build-info.ts", root);
const content = `// Generated by bun run code:generate; excludes tests and this generated file.\nexport const CODE_REVISION =\n  "${revision}";\n`;
if (process.argv.includes("--check")) {
  if (
    !(await Bun.file(target).exists()) ||
    (await Bun.file(target).text()) !== content
  )
    throw new Error("Code revision is stale; run bun run code:generate");
} else await Bun.write(target, content);
console.info(`Code revision: ${revision}`);
